#+title: CPython
#+subtitle: Stuff you probably didn't know about Python
#+author: Vincent De Comarmond
# #+SETUPFILE: /home/vincentdecomarmond/PersonalProjects/org-themes/src/readtheorg_inline/readtheorg_inline.theme
#+OPTIONS: toc:2 
#+OPTIONS: ^:nil
#+OPTIONS: \n:t

#+BEGIN_COMMENT
Rejected export themes

#+SETUPFILE: /home/vincentdecomarmond/PersonalProjects/org-themes/src/bigblow_inline/bigblow_inline.theme
#+SETUPFILE: /home/vincentdecomarmond/PersonalProjects/org-themes/src/comfy_inline/comfy_inline.theme
#+SETUPFILE: /home/vincentdecomarmond/PersonalProjects/org-themes/src/gray/gray.theme
#+SETUPFILE: /home/vincentdecomarmond/PersonalProjects/org-themes/src/imagine_light/imagine_light.theme
#+SETUPFILE: /home/vincentdecomarmond/PersonalProjects/org-themes/src/latexcss/latexcss.theme
#+SETUPFILE: /home/vincentdecomarmond/PersonalProjects/org-themes/src/readtheorg_inline/readtheorg_inline.theme
#+SETUPFILE: /home/vincentdecomarmond/PersonalProjects/org-themes/src/rethink_inline/rethink_inline.theme
#+SETUPFILE: /home/vincentdecomarmond/PersonalProjects/org-themes/src/retro_dark/retro_dark.theme
#+SETUPFILE: /home/vincentdecomarmond/PersonalProjects/org-themes/src/simple_gray/simple_gray.theme
#+SETUPFILE: /home/vincentdecomarmond/PersonalProjects/org-themes/src/simple_inline/simple_inline.theme
#+SETUPFILE: /home/vincentdecomarmond/PersonalProjects/org-themes/src/simple_white/simple_white.theme
#+SETUPFILE: /home/vincentdecomarmond/PersonalProjects/org-themes/src/simple_whiteblue/simple_whiteblue.theme
#+SETUPFILE: /home/vincentdecomarmond/PersonalProjects/org-themes/src/solarized_dark/solarized_dark.theme
#+SETUPFILE: /home/vincentdecomarmond/PersonalProjects/org-themes/src/solarized_dark/solarized_dark.theme
#+SETUPFILE: /home/vincentdecomarmond/PersonalProjects/org-themes/src/solarized_light/solarized_light.theme
#+SETUPFILE: /home/vincentdecomarmond/PersonalProjects/org-themes/src/stylish_white/stylish_white.theme
#+SETUPFILE: /home/vincentdecomarmond/PersonalProjects/org-themes/src/white_clean/white_clean.theme
#+END_COMMENT


** DISCLAIMER:
I am not an expert in any of the following Not at all. So ... whatever you see below might be (and probably is) very badly done. The algorithms are definitely not very efficient and the way everything is glued together is probably sub-optimal or plain bad.

The project can be cloned from here:
+ ~git clone https://github.com/Vincent-de-Comarmond/cpython-extension.git~
+ ~git clone git@github.com:Vincent-de-Comarmond/cpython-extension.git~
+ https://github.com/Vincent-de-Comarmond/cpython-extension

** Key resources:

+ [[http://saidvandeklundert.net/learn/2022-06-02-extending-python-with-c/][Extending Python with C]]
+ [[https://realpython.com/build-python-c-extension-module/][Building a Python C Extension Module]]
+ [[https://docs.python.org/3/extending/extending.html][Extending Python with C or C++]]

* Preamble: WTF is CPython

What you know as Python is actually [[https://github.com/python/cpython][CPython]]. It is the [[https://en.wikipedia.org/wiki/CPython][reference/standard implementation]] of the Python programming language and the most common (by far). [[https://www.python.org/download/alternatives/][Other implementations]] do exist and are used in various contexts. So the long of the short of this is that Python/CPython (I won't differentiate between the two anymore) is actually an interpreted language written in C. I.e. it is something like translator/interpreter of a string/text-file written in [[https://www.cprogramming.com/][C]].

Let's think about why this is. An interpreted language (i.e. one that's not compiled to machine code) cannot run on hardware by itself. This is because hardware cannot understand "words" or strings. Computer chips understand electrical inputs in the form of 0s and 1s. Ultimately everything needs to get cooked down to this. Whatever is translating your Python to 0s and 1s cannot be the same words you see - at some stage whatever is interpreting Python must change the words to numbers. For this compiled/machine code is necessary.


** So ... like how is this useful?

Have you ever wondered how [[https://numpy.org/][Numpy]] (for example) is so fast compared to pure python? Or why anybody would choose [[https://pandas.pydata.org/][Pandas']] very non-pythonic syntax? The reason Pandas is useful is because it's faster than "normal Python" one you're working with more than a trivial amount of data.

The reason both of these libraries are "faster" than writing things by hand in Python is where the C in CPython comes in.
+ The standard Python is written in C
+ Is it possible to extend the "standard" Python by writing libraries in C (or even just extend the language itself)?
  + It turns out that this is indeed possible (though let's leave modifying the language itself to the professionals).

* The project: Make a C-based library to extend Python

So ... let us try to make a C-extension to Python. Let's do something computationally-intensive (like finding prime numbers).

** What the project looks like:

#+BEGIN_EXAMPLE
.
├── LICENSE
├── pure_c
│   ├── primefinderfunc.c
│   ├── primefinderfunc.h
│   └── primefindermain.c
├── python_extension     # This is the working directory
│   ├── primefinder.c
│   ├── primefinderfunc.c
│   ├── primefinderfunc.h
│   ├── setup.py
│   ├── speedtest.py
│   ├── tests_prime_finding.py
└── README.org
#+END_EXAMPLE

Feel free to ignore the ~pure_c~ directory. This is where I tested my algorithm using purely C to ensure it worked before trying to convert it to a Python extension.


* The C code

Note again -  I am not an expert in this. So this stuff is ... very sketchy at best. I've tried to comment/document the code to make it as understandable as possible. Please read the comments for direction.

** ~python_extension/primefinderfunc.c~

This contains the function which computes primes. Note the statement ~#include <stdbool.h>~ - this is how one does imports in C. Note that the function ~generatePrimes~ does not return anything, but populates the array given to it. This is because one can't really return an array from a function in C (this is a bit of a complicated question).

The code here is pretty simple.

** ~python_extension/primefinderfunc.h~

This is how we make things exportable in C. There is nearly nothing here except the function stub ~void generatePrimes(int, long[]);~. The C pre-processor finds the function body (defined above in ~python_extension/primefinderfunc.c~) based on the function signature of this stub and copies the function to wherever one writes ~#include "primefinderfunc.h"~, thereby making it visible in other scripts.

Note also the code:
#+BEGIN_SRC C
  #ifndef PRIMEFINDERFUNC_H
  #define PRIMEFINDERFUNC_H
  // ...
  #endif
#+END_SRC

This simply prevents the code in the header (~.h~ file) from being read multiple times (in a more complicated project) which would cause an error.


* Installing

+ ~pip install -r requirements.txt~: Install setuptools ... this is needed to install the c-exension
+ ~pip install .~: Install our c-extension
